#!/bin/sh
# squash commit from <hash> to HEAD
# USAGE:
# git squash <ref>

HINT="git squash <ref>"
ARGS=("$@")
HASH="${ARGS[0]}"
REST="${ARGS[@]:1}"

STATUS=$(git status -s)
if [ "$STATUS" != "" ]; then
  echo "Git is not clean"
  exit 1
fi

CURRENT_HASH=$(git log --pretty=format:'%H' HEAD^..HEAD)

if [ "$HASH" == "" ]; then
  echo "Hash must be specified"
  echo ""
  echo "\033[1mUSAGE:\033[0m " "$HINT"
  echo ""
  exit 1
fi

OUTPUT=$(git log --graph --pretty=format:'%s' "$HASH"..HEAD)
TEMPFILE=$(mktemp /tmp/git-squash-commit-XXXXX)
trap "rm -f \"$TEMPFILE\"" exit

echo '\n' >> "$TEMPFILE"
git log --graph --pretty=format:'%s' "$HASH"..HEAD >> "$TEMPFILE"
echo '' >> "$TEMPFILE"

trap "git reset --hard \"$CURRENT_HASH\"" INT QUIT ABRT TERM

git reset --soft "$HASH"
git commit $REST -t "$TEMPFILE"
