#!/bin/sh
# squash commit from <hash> to HEAD

HINT="git squash <hash>"

STATUS=$(git status -s)
if [ "$STATUS" != "" ]; then
  echo "Git is not clean"
  exit 1
fi

CURRENT_HASH=$(git log --pretty=format:'%H' HEAD^..HEAD)

if [ "$1" == "" ]; then
  echo "Hash must be specified"
  echo ""
  echo "\033[1mUSAGE:\033[0m " $HINT
  echo ""
  exit 1
fi

OUTPUT=$(git log --graph --pretty=format:'%s' $1..HEAD)
TEMPFILE=$(mktemp /tmp/git-squash-commit-XXXXX)
trap "rm -f $TEMPFILE" exit

echo '\n' >> $TEMPFILE
git log --graph --pretty=format:'%s' $1..HEAD >> $TEMPFILE
echo '' >> $TEMPFILE

git reset --soft "$1"

if [ "$?" != "0" ]; then
  git reset --hard $CURRENT_HASH
  exit 1
fi

git commit -t $TEMPFILE
if [ "$?" != "0" ]; then
  git reset --hard $CURRENT_HASH
  exit 1
fi
